import { index, pgEnum, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { conversations } from "@/schema";

/**
 * Role of a message participant:
 * - user      - typed by the customer.
 * - assistant - generated by the LLM
 * - tool      - result returned by a tool call
 */
export const messageRole = pgEnum("message_role", [
	"user",
	"assistant",
	"tool",
]);

export type MessageRole = (typeof messageRole.enumValues)[number];

/**
 * A single message in an agent conversation.
 */
export const messages = pgTable(
	"messages",
	{
		id: text("id").primaryKey(),

		/**
		 * The conversation this message belongs to.
		 * Deleted when the conversation is deleted.
		 */
		conversationId: text("conversation_id")
			.notNull()
			.references(() => conversations.id, { onDelete: "cascade" }),

		/**
		 * Who produced this message:
		 * - user      - typed by the customer.
		 * - assistant - generated by the LLM, may be empty string when role is tool-call-only.
		 * - tool      - JSON-serialized result returned by a tool.
		 */
		role: messageRole("role").notNull(),

		/**
		 * Text content of the message:
		 * - For `tool` messages this is the JSON-serialized tool result.
		 * - For `assistant` messages that trigger tool calls, this is the model's
		 *   text portion (may be an empty string when the turn is tool-call-only).
		 */
		content: text("content").notNull(),

		/**
		 * Name of the tool invoked. Only set when role = 'tool'.
		 */
		toolName: text("tool_name"),

		/**
		 * Correlation ID linking an assistant tool-call request to its result.
		 * Set on both the assistant message that triggers the call and the
		 * corresponding tool message that carries the result.
		 */
		toolCallId: text("tool_call_id"),

		/**
		 * Timestamp of message creation. Used for chronological retrieval
		 * and conversation replay.
		 */
		createdAt: timestamp("created_at", { withTimezone: true })
			.notNull()
			.defaultNow(),
	},

	(t) => [
		/**
		 * Chronological message retrieval for a conversation.
		 */
		index("messages_conversation_id_idx").on(t.conversationId),

		/**
		 * Look up a specific tool result by its correlation ID.
		 */
		index("messages_tool_call_id_idx").on(t.toolCallId),
	],
);

export type Message = typeof messages.$inferSelect;
export type MessageDraft = typeof messages.$inferInsert;
