/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorefrontRouteRouteImport } from './routes/_storefront/route'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as StorefrontIndexRouteImport } from './routes/_storefront/index'
import { Route as StorefrontCheckoutRouteRouteImport } from './routes/_storefront/checkout/route'
import { Route as StorefrontCheckoutIndexRouteImport } from './routes/_storefront/checkout/index'
import { Route as StorefrontProductsSlugRouteImport } from './routes/_storefront/products/$slug'
import { Route as StorefrontOrderConfirmationIdRouteImport } from './routes/_storefront/order-confirmation/$id'
import { Route as StorefrontCategoriesSplatRouteImport } from './routes/_storefront/categories/$'

const StorefrontRouteRoute = StorefrontRouteRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontCheckoutRouteRoute = StorefrontCheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontCheckoutIndexRoute = StorefrontCheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontCheckoutRouteRoute,
} as any)
const StorefrontProductsSlugRoute = StorefrontProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const StorefrontOrderConfirmationIdRoute =
  StorefrontOrderConfirmationIdRouteImport.update({
    id: '/order-confirmation/$id',
    path: '/order-confirmation/$id',
    getParentRoute: () => StorefrontRouteRoute,
  } as any)
const StorefrontCategoriesSplatRoute =
  StorefrontCategoriesSplatRouteImport.update({
    id: '/categories/$',
    path: '/categories/$',
    getParentRoute: () => StorefrontRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StorefrontIndexRoute
  '/checkout': typeof StorefrontCheckoutRouteRouteWithChildren
  '/agent/': typeof AgentIndexRoute
  '/categories/$': typeof StorefrontCategoriesSplatRoute
  '/order-confirmation/$id': typeof StorefrontOrderConfirmationIdRoute
  '/products/$slug': typeof StorefrontProductsSlugRoute
  '/checkout/': typeof StorefrontCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof StorefrontIndexRoute
  '/agent': typeof AgentIndexRoute
  '/categories/$': typeof StorefrontCategoriesSplatRoute
  '/order-confirmation/$id': typeof StorefrontOrderConfirmationIdRoute
  '/products/$slug': typeof StorefrontProductsSlugRoute
  '/checkout': typeof StorefrontCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_storefront': typeof StorefrontRouteRouteWithChildren
  '/_storefront/checkout': typeof StorefrontCheckoutRouteRouteWithChildren
  '/_storefront/': typeof StorefrontIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/_storefront/categories/$': typeof StorefrontCategoriesSplatRoute
  '/_storefront/order-confirmation/$id': typeof StorefrontOrderConfirmationIdRoute
  '/_storefront/products/$slug': typeof StorefrontProductsSlugRoute
  '/_storefront/checkout/': typeof StorefrontCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/agent/'
    | '/categories/$'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/categories/$'
    | '/order-confirmation/$id'
    | '/products/$slug'
    | '/checkout'
  id:
    | '__root__'
    | '/_storefront'
    | '/_storefront/checkout'
    | '/_storefront/'
    | '/agent/'
    | '/_storefront/categories/$'
    | '/_storefront/order-confirmation/$id'
    | '/_storefront/products/$slug'
    | '/_storefront/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StorefrontRouteRoute: typeof StorefrontRouteRouteWithChildren
  AgentIndexRoute: typeof AgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/checkout': {
      id: '/_storefront/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StorefrontCheckoutRouteRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/checkout/': {
      id: '/_storefront/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof StorefrontCheckoutIndexRouteImport
      parentRoute: typeof StorefrontCheckoutRouteRoute
    }
    '/_storefront/products/$slug': {
      id: '/_storefront/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof StorefrontProductsSlugRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/order-confirmation/$id': {
      id: '/_storefront/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof StorefrontOrderConfirmationIdRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_storefront/categories/$': {
      id: '/_storefront/categories/$'
      path: '/categories/$'
      fullPath: '/categories/$'
      preLoaderRoute: typeof StorefrontCategoriesSplatRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
  }
}

interface StorefrontCheckoutRouteRouteChildren {
  StorefrontCheckoutIndexRoute: typeof StorefrontCheckoutIndexRoute
}

const StorefrontCheckoutRouteRouteChildren: StorefrontCheckoutRouteRouteChildren =
  {
    StorefrontCheckoutIndexRoute: StorefrontCheckoutIndexRoute,
  }

const StorefrontCheckoutRouteRouteWithChildren =
  StorefrontCheckoutRouteRoute._addFileChildren(
    StorefrontCheckoutRouteRouteChildren,
  )

interface StorefrontRouteRouteChildren {
  StorefrontCheckoutRouteRoute: typeof StorefrontCheckoutRouteRouteWithChildren
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontCategoriesSplatRoute: typeof StorefrontCategoriesSplatRoute
  StorefrontOrderConfirmationIdRoute: typeof StorefrontOrderConfirmationIdRoute
  StorefrontProductsSlugRoute: typeof StorefrontProductsSlugRoute
}

const StorefrontRouteRouteChildren: StorefrontRouteRouteChildren = {
  StorefrontCheckoutRouteRoute: StorefrontCheckoutRouteRouteWithChildren,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontCategoriesSplatRoute: StorefrontCategoriesSplatRoute,
  StorefrontOrderConfirmationIdRoute: StorefrontOrderConfirmationIdRoute,
  StorefrontProductsSlugRoute: StorefrontProductsSlugRoute,
}

const StorefrontRouteRouteWithChildren = StorefrontRouteRoute._addFileChildren(
  StorefrontRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StorefrontRouteRoute: StorefrontRouteRouteWithChildren,
  AgentIndexRoute: AgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
