import { db } from "@db/db";
import { type ProductVariantDraft, productVariants } from "@db/schema";

const VARIANTS: ProductVariantDraft[] = [
	{
		id: "var_cleanser_001_a",
		productId: "prod_cleanser_001",
		sku: "PL-HGC-150ML",
		name: "150ml",
		priceInCents: 1495,
		stockQuantity: 120,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_cleanser_001_b",
		productId: "prod_cleanser_001",
		sku: "PL-HGC-300ML",
		name: "300ml Value Size",
		priceInCents: 2295,
		stockQuantity: 60,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_cleanser_002_a",
		productId: "prod_cleanser_002",
		sku: "VD-CFW-120ML",
		name: "120ml",
		priceInCents: 1295,
		stockQuantity: 100,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_cleanser_002_b",
		productId: "prod_cleanser_002",
		sku: "VD-CFW-240ML",
		name: "240ml Duo Size",
		priceInCents: 2195,
		stockQuantity: 45,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_toner_001_a",
		productId: "prod_toner_001",
		sku: "LM-HRT-100ML",
		name: "100ml Travel Size",
		priceInCents: 1095,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_toner_001_b",
		productId: "prod_toner_001",
		sku: "LM-HRT-200ML",
		name: "200ml",
		priceInCents: 1695,
		stockQuantity: 110,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_toner_002_a",
		productId: "prod_toner_002",
		sku: "PL-AGT-150ML",
		name: "150ml",
		priceInCents: 1895,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_toner_002_b",
		productId: "prod_toner_002",
		sku: "PL-AGT-300ML",
		name: "300ml Refill",
		priceInCents: 3195,
		stockQuantity: 40,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_serum_001_a",
		productId: "prod_serum_001",
		sku: "VD-VCB-30ML",
		name: "30ml",
		priceInCents: 3495,
		stockQuantity: 75,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_serum_001_b",
		productId: "prod_serum_001",
		sku: "VD-VCB-50ML",
		name: "50ml",
		priceInCents: 4995,
		stockQuantity: 35,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_serum_002_a",
		productId: "prod_serum_002",
		sku: "LM-HAP-10ML",
		name: "10ml Mini",
		priceInCents: 1295,
		stockQuantity: 60,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_serum_002_b",
		productId: "prod_serum_002",
		sku: "LM-HAP-30ML",
		name: "30ml",
		priceInCents: 2895,
		stockQuantity: 100,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_serum_002_c",
		productId: "prod_serum_002",
		sku: "LM-HAP-50ML",
		name: "50ml",
		priceInCents: 4295,
		stockQuantity: 30,
		isAvailable: true,
		position: 3,
	},
	{
		id: "var_moist_001_a",
		productId: "prod_moisturiser_001",
		sku: "PL-BRD-30ML",
		name: "30ml Travel Size",
		priceInCents: 1495,
		stockQuantity: 70,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_moist_001_b",
		productId: "prod_moisturiser_001",
		sku: "PL-BRD-50ML",
		name: "50ml",
		priceInCents: 2295,
		stockQuantity: 115,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_moist_002_a",
		productId: "prod_moisturiser_002",
		sku: "VD-MCG-50ML",
		name: "50ml",
		priceInCents: 1995,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_moist_002_b",
		productId: "prod_moisturiser_002",
		sku: "VD-MCG-100ML",
		name: "100ml",
		priceInCents: 3295,
		stockQuantity: 45,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_face_oil_001_a",
		productId: "prod_face_oil_001",
		sku: "LM-RRO-10ML",
		name: "10ml Trial",
		priceInCents: 1295,
		stockQuantity: 55,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_oil_001_b",
		productId: "prod_face_oil_001",
		sku: "LM-RRO-30ML",
		name: "30ml",
		priceInCents: 2695,
		stockQuantity: 80,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_face_oil_002_a",
		productId: "prod_face_oil_002",
		sku: "PL-SBO-30ML",
		name: "30ml",
		priceInCents: 1895,
		stockQuantity: 95,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_oil_002_b",
		productId: "prod_face_oil_002",
		sku: "PL-SBO-50ML",
		name: "50ml",
		priceInCents: 2795,
		stockQuantity: 40,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_eye_001_a",
		productId: "prod_eye_cream_001",
		sku: "VD-BEC-15ML",
		name: "15ml",
		priceInCents: 2895,
		stockQuantity: 65,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_eye_002_a",
		productId: "prod_eye_cream_002",
		sku: "LM-DEG-15ML",
		name: "15ml",
		priceInCents: 2495,
		stockQuantity: 70,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_mask_001_a",
		productId: "prod_face_mask_001",
		sku: "PL-HBS-SINGLE",
		name: "Single Mask",
		priceInCents: 595,
		stockQuantity: 200,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_mask_001_b",
		productId: "prod_face_mask_001",
		sku: "PL-HBS-5PK",
		name: "Pack of 5",
		priceInCents: 2295,
		stockQuantity: 85,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_face_mask_001_c",
		productId: "prod_face_mask_001",
		sku: "PL-HBS-10PK",
		name: "Pack of 10",
		priceInCents: 3995,
		compareAtPriceInCents: 5950,
		stockQuantity: 40,
		isAvailable: true,
		position: 3,
	},
	{
		id: "var_face_mask_002_a",
		productId: "prod_face_mask_002",
		sku: "VD-PCM-75ML",
		name: "75ml",
		priceInCents: 1695,
		stockQuantity: 100,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_mask_002_b",
		productId: "prod_face_mask_002",
		sku: "VD-PCM-150ML",
		name: "150ml Refill",
		priceInCents: 2795,
		stockQuantity: 45,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_exfoliant_001_a",
		productId: "prod_exfoliant_001",
		sku: "LM-GAR-30ML",
		name: "30ml",
		priceInCents: 2295,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_exfoliant_001_b",
		productId: "prod_exfoliant_001",
		sku: "LM-GAR-100ML",
		name: "100ml",
		priceInCents: 5995,
		stockQuantity: 30,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_exfoliant_002_a",
		productId: "prod_exfoliant_002",
		sku: "PL-BPR-30ML",
		name: "30ml",
		priceInCents: 1995,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_spf_001_a",
		productId: "prod_face_spf_001",
		sku: "VD-ISF-30ML",
		name: "30ml Travel Size",
		priceInCents: 1695,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_face_spf_001_b",
		productId: "prod_face_spf_001",
		sku: "VD-ISF-50ML",
		name: "50ml",
		priceInCents: 2695,
		stockQuantity: 130,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_face_spf_001_c",
		productId: "prod_face_spf_001",
		sku: "VD-ISF-100ML",
		name: "100ml",
		priceInCents: 4595,
		stockQuantity: 50,
		isAvailable: true,
		position: 3,
	},
	{
		id: "var_face_spf_002_a",
		productId: "prod_face_spf_002",
		sku: "LM-TSM-50ML",
		name: "50ml",
		priceInCents: 2295,
		stockQuantity: 100,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_spf_001_a",
		productId: "prod_body_spf_001",
		sku: "PL-SBL-100ML",
		name: "100ml Travel Size",
		priceInCents: 1195,
		stockQuantity: 100,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_spf_001_b",
		productId: "prod_body_spf_001",
		sku: "PL-SBL-200ML",
		name: "200ml",
		priceInCents: 1895,
		stockQuantity: 140,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_body_spf_001_c",
		productId: "prod_body_spf_001",
		sku: "PL-SBL-400ML",
		name: "400ml Family Size",
		priceInCents: 2995,
		stockQuantity: 55,
		isAvailable: true,
		position: 3,
	},
	{
		id: "var_body_spf_002_a",
		productId: "prod_body_spf_002",
		sku: "VD-SBS-100ML",
		name: "100ml",
		priceInCents: 995,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_spf_002_b",
		productId: "prod_body_spf_002",
		sku: "VD-SBS-200ML",
		name: "200ml",
		priceInCents: 1595,
		stockQuantity: 110,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_after_sun_001_a",
		productId: "prod_after_sun_001",
		sku: "LM-CAG-100ML",
		name: "100ml",
		priceInCents: 695,
		stockQuantity: 100,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_after_sun_001_b",
		productId: "prod_after_sun_001",
		sku: "LM-CAG-200ML",
		name: "200ml",
		priceInCents: 1095,
		stockQuantity: 130,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_after_sun_002_a",
		productId: "prod_after_sun_002",
		sku: "PL-SAL-250ML",
		name: "250ml",
		priceInCents: 1295,
		stockQuantity: 95,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_after_sun_002_b",
		productId: "prod_after_sun_002",
		sku: "PL-SAL-500ML",
		name: "500ml",
		priceInCents: 2095,
		stockQuantity: 40,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_body_lotion_001_a",
		productId: "prod_body_lotion_001",
		sku: "VD-DMB-150ML",
		name: "150ml",
		priceInCents: 995,
		stockQuantity: 75,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_lotion_001_b",
		productId: "prod_body_lotion_001",
		sku: "VD-DMB-300ML",
		name: "300ml",
		priceInCents: 1695,
		stockQuantity: 120,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_body_lotion_002_a",
		productId: "prod_body_lotion_002",
		sku: "LM-EBL-200ML",
		name: "200ml",
		priceInCents: 695,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_lotion_002_b",
		productId: "prod_body_lotion_002",
		sku: "LM-EBL-400ML",
		name: "400ml",
		priceInCents: 1095,
		stockQuantity: 130,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_body_wash_001_a",
		productId: "prod_body_wash_001",
		sku: "PL-SSC-150ML",
		name: "150ml Travel Size",
		priceInCents: 695,
		stockQuantity: 85,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_wash_001_b",
		productId: "prod_body_wash_001",
		sku: "PL-SSC-300ML",
		name: "300ml",
		priceInCents: 1095,
		stockQuantity: 150,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_body_wash_002_a",
		productId: "prod_body_wash_002",
		sku: "VD-ECG-300ML",
		name: "300ml",
		priceInCents: 895,
		stockQuantity: 160,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_wash_002_b",
		productId: "prod_body_wash_002",
		sku: "VD-ECG-500ML",
		name: "500ml Jumbo",
		priceInCents: 1295,
		stockQuantity: 65,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_body_scrub_001_a",
		productId: "prod_body_scrub_001",
		sku: "LM-BSB-250ML",
		name: "250ml",
		priceInCents: 1395,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_scrub_002_a",
		productId: "prod_body_scrub_002",
		sku: "VD-CCB-250ML",
		name: "250ml",
		priceInCents: 1495,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_body_scrub_002_b",
		productId: "prod_body_scrub_002",
		sku: "VD-CCB-500ML",
		name: "500ml",
		priceInCents: 2495,
		compareAtPriceInCents: 2990,
		stockQuantity: 35,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_hand_001_a",
		productId: "prod_hand_cream_001",
		sku: "PL-IHR-30ML",
		name: "30ml Travel Size",
		priceInCents: 695,
		stockQuantity: 100,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_hand_001_b",
		productId: "prod_hand_cream_001",
		sku: "PL-IHR-75ML",
		name: "75ml",
		priceInCents: 1295,
		stockQuantity: 130,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_hand_001_c",
		productId: "prod_hand_cream_001",
		sku: "PL-IHR-150ML",
		name: "150ml Value",
		priceInCents: 2095,
		stockQuantity: 50,
		isAvailable: true,
		position: 3,
	},
	{
		id: "var_hand_002_a",
		productId: "prod_hand_cream_002",
		sku: "LM-RVE-30ML",
		name: "30ml",
		priceInCents: 495,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_hand_002_b",
		productId: "prod_hand_cream_002",
		sku: "LM-RVE-75ML",
		name: "75ml",
		priceInCents: 895,
		stockQuantity: 140,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_foot_001_a",
		productId: "prod_foot_care_001",
		sku: "VD-CHR-60ML",
		name: "60ml",
		priceInCents: 1095,
		stockQuantity: 85,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_foot_001_b",
		productId: "prod_foot_care_001",
		sku: "VD-CHR-125ML",
		name: "125ml",
		priceInCents: 1795,
		stockQuantity: 40,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_foot_002_a",
		productId: "prod_foot_care_002",
		sku: "PL-OFM-100ML",
		name: "100ml",
		priceInCents: 1195,
		stockQuantity: 70,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_shampoo_001_a",
		productId: "prod_shampoo_001",
		sku: "LM-VLS-100ML",
		name: "100ml Travel Size",
		priceInCents: 695,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_shampoo_001_b",
		productId: "prod_shampoo_001",
		sku: "LM-VLS-300ML",
		name: "300ml",
		priceInCents: 1595,
		stockQuantity: 150,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_shampoo_001_c",
		productId: "prod_shampoo_001",
		sku: "LM-VLS-500ML",
		name: "500ml Salon Size",
		priceInCents: 2395,
		stockQuantity: 55,
		isAvailable: true,
		position: 3,
	},
	{
		id: "var_shampoo_002_a",
		productId: "prod_shampoo_002",
		sku: "VD-MRS-300ML",
		name: "300ml",
		priceInCents: 1695,
		stockQuantity: 130,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_shampoo_002_b",
		productId: "prod_shampoo_002",
		sku: "VD-MRS-500ML",
		name: "500ml Salon Size",
		priceInCents: 2495,
		stockQuantity: 50,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_cond_001_a",
		productId: "prod_conditioner_001",
		sku: "PL-SDC-300ML",
		name: "300ml",
		priceInCents: 1495,
		stockQuantity: 130,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_cond_001_b",
		productId: "prod_conditioner_001",
		sku: "PL-SDC-500ML",
		name: "500ml Salon Size",
		priceInCents: 2295,
		stockQuantity: 50,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_cond_002_a",
		productId: "prod_conditioner_002",
		sku: "LM-CDL-100ML",
		name: "100ml Travel Size",
		priceInCents: 895,
		stockQuantity: 65,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_cond_002_b",
		productId: "prod_conditioner_002",
		sku: "LM-CDL-250ML",
		name: "250ml",
		priceInCents: 1795,
		stockQuantity: 110,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_hair_mask_001_a",
		productId: "prod_hair_mask_001",
		sku: "VD-BRH-250ML",
		name: "250ml",
		priceInCents: 2695,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_hair_mask_002_a",
		productId: "prod_hair_mask_002",
		sku: "PL-MSH-150ML",
		name: "150ml",
		priceInCents: 1295,
		stockQuantity: 70,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_hair_mask_002_b",
		productId: "prod_hair_mask_002",
		sku: "PL-MSH-300ML",
		name: "300ml",
		priceInCents: 1995,
		stockQuantity: 100,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_scalp_001_a",
		productId: "prod_scalp_001",
		sku: "LM-ADS-100ML",
		name: "100ml",
		priceInCents: 2295,
		stockQuantity: 75,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_scalp_002_a",
		productId: "prod_scalp_002",
		sku: "VD-HGT-100ML",
		name: "100ml",
		priceInCents: 3295,
		stockQuantity: 60,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_scalp_002_b",
		productId: "prod_scalp_002",
		sku: "VD-HGT-200ML",
		name: "200ml (2-month supply)",
		priceInCents: 5795,
		compareAtPriceInCents: 6590,
		stockQuantity: 30,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_mens_moist_001_a",
		productId: "prod_mens_moist_001",
		sku: "EL-MDF-50ML",
		name: "50ml",
		priceInCents: 1895,
		stockQuantity: 95,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_mens_moist_001_b",
		productId: "prod_mens_moist_001",
		sku: "EL-MDF-100ML",
		name: "100ml",
		priceInCents: 3195,
		stockQuantity: 40,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_mens_moist_002_a",
		productId: "prod_mens_moist_002",
		sku: "PL-MPM-75ML",
		name: "75ml",
		priceInCents: 1595,
		stockQuantity: 85,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_shaving_001_a",
		productId: "prod_shaving_001",
		sku: "VD-PSG-75ML",
		name: "75ml Travel Size",
		priceInCents: 695,
		stockQuantity: 80,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_shaving_001_b",
		productId: "prod_shaving_001",
		sku: "VD-PSG-150ML",
		name: "150ml",
		priceInCents: 1095,
		stockQuantity: 110,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_shaving_002_a",
		productId: "prod_shaving_002",
		sku: "LM-SAB-75ML",
		name: "75ml",
		priceInCents: 1495,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_lip_001_a",
		productId: "prod_lip_001",
		sku: "PL-IRL-10ML",
		name: "10ml Single",
		priceInCents: 695,
		stockQuantity: 200,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_lip_001_b",
		productId: "prod_lip_001",
		sku: "PL-IRL-3PK",
		name: "Pack of 3",
		priceInCents: 1795,
		compareAtPriceInCents: 2085,
		stockQuantity: 75,
		isAvailable: true,
		position: 2,
	},
	{
		id: "var_lip_002_a",
		productId: "prod_lip_002",
		sku: "LM-OLM-15ML",
		name: "15ml",
		priceInCents: 1195,
		stockQuantity: 90,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_gift_001_a",
		productId: "prod_gift_001",
		sku: "LM-GSF-STD",
		name: "Standard Set",
		priceInCents: 4995,
		compareAtPriceInCents: 5985,
		stockQuantity: 50,
		isAvailable: true,
		position: 1,
	},
	{
		id: "var_gift_002_a",
		productId: "prod_gift_002",
		sku: "VD-SDB-STD",
		name: "Standard Set",
		priceInCents: 3995,
		compareAtPriceInCents: 4385,
		stockQuantity: 45,
		isAvailable: true,
		position: 1,
	},
];

export async function seedProductVariants(): Promise<void> {
	console.log(`Seeding ${VARIANTS.length} product variants…`);

	await db.insert(productVariants).values(VARIANTS).onConflictDoNothing();

	console.log("Product variant seed complete successfully.");
}

seedProductVariants()
	.then(() => process.exit(0))
	.catch((err: unknown) => {
		console.error("Product variant seed failed:", err);
		process.exit(1);
	});
